### ISSUE TITLE
Other datasets not listed

### ISSUE THREAD

**Issue by Hamzah-Luqman** [ZechengLi19/Awesome-Sign-Language#1]
I think these datasets should be added to the list:
- [KArSL ](https://hamzah-luqman.github.io/KArSL/)(Isolated dataset)
- [ArabSign ](https://hamzah-luqman.github.io/ArabSign/)(Continuous dataset)

**Comment by ZechengLi19** [comment]
> I think these datasets should be added to the list:
> 
> * [KArSL ](https://hamzah-luqman.github.io/KArSL/)(Isolated dataset)
> * [ArabSign ](https://hamzah-luqman.github.io/ArabSign/)(Continuous dataset)

Good suggestion! Two datasets will be added in the next version!

**Comment by ZechengLi19** [comment]
> I think these datasets should be added to the list:
> 
> * [KArSL ](https://hamzah-luqman.github.io/KArSL/)(Isolated dataset)
> * [ArabSign ](https://hamzah-luqman.github.io/ArabSign/)(Continuous dataset)

But I found that in the datasets you provided, the number of samples of the train/test/dev dataset cannot be found in the paper. Can you tell me so that I can add the datasets you mentioned?

**Comment by Hamzah-Luqman** [comment]
All the details are mentioned on our papers including number of samples.
